### ISSUE TITLE
Data model for `meterServiceAllowList`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-meter-usage-reporter#4]
https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/0fca317d8b2f3d229a38f29dd3f730c500922500/lib/meters.js#L496-L509

https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/0fca317d8b2f3d229a38f29dd3f730c500922500/lib/config.js#L36-L37

Can this be simplified such that `config['meter-usage-reporter'].meterServiceAllowList` can be host names instead of URLs?

When meter is added, it is only necessary to ensure that the new meter host is allowed, without respect for the path/protocol or anything else, is that correct?

**Comment by mattcollier** [comment]
Or I wonder if specifying the exact meter ID (full URL) would be the appropriate setting.

**Comment by mattcollier** [comment]
I *think* I now understand what you're trying to accomplish in the inverse:
```
allowlist: [
  'https://my.meter.server/safe/meters',
  'https://my.meter.server/safe-v2/meters',
```

So when you said you want to allow for different root paths, you mean that you would like the root path to be configurable, but ALSO described as part of the configuration for validation purposes.  I was thinking the path could be a hard coded part of the validation process.

All that said, if the attacker controls `my.meter.server` and they control `https://my.meter.server/safe/meters`, that means they also control `https://my.meter.server/safe/meters/relay-to-twitter`.  Doesn't this circumvent the protections we're trying to put into place.

If I control the `my.meter.server` domain, and `my.meter.server` is in the `allowList` on the KMS system, there is no way the allow list can protect me from myself is there?  One could put "relay-to-twitter" code on ANY endpoint and the KMS can't possibly know about that right?

Therefore, I think simply checking the `hostname` or `host` is appropriate.

**Comment by dlongley** [comment]
> If I control the my.meter.server domain, and my.meter.server is in the allowList on the KMS system, there is no way the allow list can protect me from myself is there?

If we include the path then I think you have some protection. Perhaps it helps to think about it like this:

The user provides this data as a meter ID:

`aaaa/bbbb/cccc/meters/1234`

We can either check `aaaa/bbbb/cccc` against an allow list -- or we can just check `aaaa`. The former prevents an attacker from swapping out `bbbb/cccc` to potentially cause some trouble (because we checked it and it didn't match). If don't check the path, then every time we add some other service to our trusted metering system like `dddd/eeee` or `ffff/gggg`, we have to remember to think about what will happen if an attacker gets our meter reporter to erroneously hit those services. We don't get a clean separation of concerns.

This is a bigger problem for configurations where all services run in a single "node" -- which is a valid configuration for a system that uses this module.

> One could put "relay-to-twitter" code on ANY endpoint and the KMS can't possibly know about that right?

If the "relay-to-twitter" endpoint isn't in the allow list (and we're checking the path) then it won't get hit because it will fail the check. If we put it at any endpoint and we're *not* checking the path, then it could get hit. We can presume that there is no "rely-to-twitter" path attached to the actual metering API per its contract (which resides at `/path/meters`). Given that presumption, as long as we check the full base URL and tack the `/meters` API on the end, we should be covered, end to end.

**Comment by dlongley** [comment]
@mattcollier,

> This says that request to add a meter with a host of my.meter.server must originate from the CIDR 8.8.8.8/32. In addition to the signature based authentication on the endpoint, this seems like an improvement.

This doesn't make sense to me. Again, this module does not add meters. It reports to them. This module acts as an http *client*, not a server, in this respect. The allow list is to control which *servers* this module will automatically hit (in a scheduled background process/operation) to report meter usage. So there's no IP to check. It works like this:

1. A background operation to report to a meter is triggered.
2. The meter usage information is gathered.
3. The meter ID to report to is checked against an allow list.
4. An http POST is made to the meter URL associated with the meter ID, transmitting the usage.

The allow list has nothing to do with any "incoming requests" to "add a meter"; there aren't any involved in this process.

**Comment by dlongley** [comment]
@mattcollier, are we able to close this issue yet?

**Comment by mattcollier** [comment]
Yes, closing.
